/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidarCarteirinhaRouteImport } from './routes/validar-carteirinha'
import { Route as TorcidaRouteImport } from './routes/torcida'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as NucleosRouteImport } from './routes/nucleos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as MeuImpactoRouteImport } from './routes/meu-impacto'
import { Route as MaoNaMassaRouteImport } from './routes/mao-na-massa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as IntegracaoNeuroinclusivaRouteImport } from './routes/integracao-neuroinclusiva'
import { Route as EmpresarialRouteImport } from './routes/empresarial'
import { Route as DoacoesRouteImport } from './routes/doacoes'
import { Route as ConvideRouteImport } from './routes/convide'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as AreaCriancaRouteImport } from './routes/area-crianca'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t/$slug'
import { Route as DoacoesObrigadoRouteImport } from './routes/doacoes.obrigado'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminLojasRouteImport } from './routes/admin.lojas'
import { Route as AdminArquibancadaRouteImport } from './routes/admin.arquibancada'

const ValidarCarteirinhaRoute = ValidarCarteirinhaRouteImport.update({
  id: '/validar-carteirinha',
  path: '/validar-carteirinha',
  getParentRoute: () => rootRouteImport,
} as any)
const TorcidaRoute = TorcidaRouteImport.update({
  id: '/torcida',
  path: '/torcida',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const NucleosRoute = NucleosRouteImport.update({
  id: '/nucleos',
  path: '/nucleos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuImpactoRoute = MeuImpactoRouteImport.update({
  id: '/meu-impacto',
  path: '/meu-impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const MaoNaMassaRoute = MaoNaMassaRouteImport.update({
  id: '/mao-na-massa',
  path: '/mao-na-massa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoNeuroinclusivaRoute =
  IntegracaoNeuroinclusivaRouteImport.update({
    id: '/integracao-neuroinclusiva',
    path: '/integracao-neuroinclusiva',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmpresarialRoute = EmpresarialRouteImport.update({
  id: '/empresarial',
  path: '/empresarial',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacoesRoute = DoacoesRouteImport.update({
  id: '/doacoes',
  path: '/doacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvideRoute = ConvideRouteImport.update({
  id: '/convide',
  path: '/convide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaCriancaRoute = AreaCriancaRouteImport.update({
  id: '/area-crianca',
  path: '/area-crianca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacoesObrigadoRoute = DoacoesObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => DoacoesRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasRoute = AdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArquibancadaRoute = AdminArquibancadaRouteImport.update({
  id: '/arquibancada',
  path: '/arquibancada',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/area-crianca': typeof AreaCriancaRoute
  '/beneficios': typeof BeneficiosRoute
  '/cadastro': typeof CadastroRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/contato': typeof ContatoRoute
  '/convide': typeof ConvideRoute
  '/doacoes': typeof DoacoesRouteWithChildren
  '/empresarial': typeof EmpresarialRoute
  '/integracao-neuroinclusiva': typeof IntegracaoNeuroinclusivaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/mao-na-massa': typeof MaoNaMassaRoute
  '/meu-impacto': typeof MeuImpactoRoute
  '/mural': typeof MuralRoute
  '/noticias': typeof NoticiasRoute
  '/nucleos': typeof NucleosRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/ranking': typeof RankingRoute
  '/termos': typeof TermosRoute
  '/torcida': typeof TorcidaRoute
  '/validar-carteirinha': typeof ValidarCarteirinhaRoute
  '/admin/arquibancada': typeof AdminArquibancadaRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/doacoes/obrigado': typeof DoacoesObrigadoRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/area-crianca': typeof AreaCriancaRoute
  '/beneficios': typeof BeneficiosRoute
  '/cadastro': typeof CadastroRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/contato': typeof ContatoRoute
  '/convide': typeof ConvideRoute
  '/doacoes': typeof DoacoesRouteWithChildren
  '/empresarial': typeof EmpresarialRoute
  '/integracao-neuroinclusiva': typeof IntegracaoNeuroinclusivaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/mao-na-massa': typeof MaoNaMassaRoute
  '/meu-impacto': typeof MeuImpactoRoute
  '/mural': typeof MuralRoute
  '/noticias': typeof NoticiasRoute
  '/nucleos': typeof NucleosRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/ranking': typeof RankingRoute
  '/termos': typeof TermosRoute
  '/torcida': typeof TorcidaRoute
  '/validar-carteirinha': typeof ValidarCarteirinhaRoute
  '/admin/arquibancada': typeof AdminArquibancadaRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/doacoes/obrigado': typeof DoacoesObrigadoRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/area-crianca': typeof AreaCriancaRoute
  '/beneficios': typeof BeneficiosRoute
  '/cadastro': typeof CadastroRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/contato': typeof ContatoRoute
  '/convide': typeof ConvideRoute
  '/doacoes': typeof DoacoesRouteWithChildren
  '/empresarial': typeof EmpresarialRoute
  '/integracao-neuroinclusiva': typeof IntegracaoNeuroinclusivaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/mao-na-massa': typeof MaoNaMassaRoute
  '/meu-impacto': typeof MeuImpactoRoute
  '/mural': typeof MuralRoute
  '/noticias': typeof NoticiasRoute
  '/nucleos': typeof NucleosRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/ranking': typeof RankingRoute
  '/termos': typeof TermosRoute
  '/torcida': typeof TorcidaRoute
  '/validar-carteirinha': typeof ValidarCarteirinhaRoute
  '/admin/arquibancada': typeof AdminArquibancadaRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/doacoes/obrigado': typeof DoacoesObrigadoRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/area-crianca'
    | '/beneficios'
    | '/cadastro'
    | '/completar-perfil'
    | '/contato'
    | '/convide'
    | '/doacoes'
    | '/empresarial'
    | '/integracao-neuroinclusiva'
    | '/lgpd'
    | '/login'
    | '/mao-na-massa'
    | '/meu-impacto'
    | '/mural'
    | '/noticias'
    | '/nucleos'
    | '/parceiros'
    | '/perfil'
    | '/privacidade'
    | '/projetos'
    | '/quem-somos'
    | '/ranking'
    | '/termos'
    | '/torcida'
    | '/validar-carteirinha'
    | '/admin/arquibancada'
    | '/admin/lojas'
    | '/admin/notificacoes'
    | '/doacoes/obrigado'
    | '/t/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/area-crianca'
    | '/beneficios'
    | '/cadastro'
    | '/completar-perfil'
    | '/contato'
    | '/convide'
    | '/doacoes'
    | '/empresarial'
    | '/integracao-neuroinclusiva'
    | '/lgpd'
    | '/login'
    | '/mao-na-massa'
    | '/meu-impacto'
    | '/mural'
    | '/noticias'
    | '/nucleos'
    | '/parceiros'
    | '/perfil'
    | '/privacidade'
    | '/projetos'
    | '/quem-somos'
    | '/ranking'
    | '/termos'
    | '/torcida'
    | '/validar-carteirinha'
    | '/admin/arquibancada'
    | '/admin/lojas'
    | '/admin/notificacoes'
    | '/doacoes/obrigado'
    | '/t/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/area-crianca'
    | '/beneficios'
    | '/cadastro'
    | '/completar-perfil'
    | '/contato'
    | '/convide'
    | '/doacoes'
    | '/empresarial'
    | '/integracao-neuroinclusiva'
    | '/lgpd'
    | '/login'
    | '/mao-na-massa'
    | '/meu-impacto'
    | '/mural'
    | '/noticias'
    | '/nucleos'
    | '/parceiros'
    | '/perfil'
    | '/privacidade'
    | '/projetos'
    | '/quem-somos'
    | '/ranking'
    | '/termos'
    | '/torcida'
    | '/validar-carteirinha'
    | '/admin/arquibancada'
    | '/admin/lojas'
    | '/admin/notificacoes'
    | '/doacoes/obrigado'
    | '/t/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AreaCriancaRoute: typeof AreaCriancaRoute
  BeneficiosRoute: typeof BeneficiosRoute
  CadastroRoute: typeof CadastroRoute
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  ContatoRoute: typeof ContatoRoute
  ConvideRoute: typeof ConvideRoute
  DoacoesRoute: typeof DoacoesRouteWithChildren
  EmpresarialRoute: typeof EmpresarialRoute
  IntegracaoNeuroinclusivaRoute: typeof IntegracaoNeuroinclusivaRoute
  LgpdRoute: typeof LgpdRoute
  LoginRoute: typeof LoginRoute
  MaoNaMassaRoute: typeof MaoNaMassaRoute
  MeuImpactoRoute: typeof MeuImpactoRoute
  MuralRoute: typeof MuralRoute
  NoticiasRoute: typeof NoticiasRoute
  NucleosRoute: typeof NucleosRoute
  ParceirosRoute: typeof ParceirosRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProjetosRoute: typeof ProjetosRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RankingRoute: typeof RankingRoute
  TermosRoute: typeof TermosRoute
  TorcidaRoute: typeof TorcidaRoute
  ValidarCarteirinhaRoute: typeof ValidarCarteirinhaRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validar-carteirinha': {
      id: '/validar-carteirinha'
      path: '/validar-carteirinha'
      fullPath: '/validar-carteirinha'
      preLoaderRoute: typeof ValidarCarteirinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torcida': {
      id: '/torcida'
      path: '/torcida'
      fullPath: '/torcida'
      preLoaderRoute: typeof TorcidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nucleos': {
      id: '/nucleos'
      path: '/nucleos'
      fullPath: '/nucleos'
      preLoaderRoute: typeof NucleosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-impacto': {
      id: '/meu-impacto'
      path: '/meu-impacto'
      fullPath: '/meu-impacto'
      preLoaderRoute: typeof MeuImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mao-na-massa': {
      id: '/mao-na-massa'
      path: '/mao-na-massa'
      fullPath: '/mao-na-massa'
      preLoaderRoute: typeof MaoNaMassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao-neuroinclusiva': {
      id: '/integracao-neuroinclusiva'
      path: '/integracao-neuroinclusiva'
      fullPath: '/integracao-neuroinclusiva'
      preLoaderRoute: typeof IntegracaoNeuroinclusivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresarial': {
      id: '/empresarial'
      path: '/empresarial'
      fullPath: '/empresarial'
      preLoaderRoute: typeof EmpresarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacoes': {
      id: '/doacoes'
      path: '/doacoes'
      fullPath: '/doacoes'
      preLoaderRoute: typeof DoacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convide': {
      id: '/convide'
      path: '/convide'
      fullPath: '/convide'
      preLoaderRoute: typeof ConvideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-crianca': {
      id: '/area-crianca'
      path: '/area-crianca'
      fullPath: '/area-crianca'
      preLoaderRoute: typeof AreaCriancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacoes/obrigado': {
      id: '/doacoes/obrigado'
      path: '/obrigado'
      fullPath: '/doacoes/obrigado'
      preLoaderRoute: typeof DoacoesObrigadoRouteImport
      parentRoute: typeof DoacoesRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas': {
      id: '/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AdminLojasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arquibancada': {
      id: '/admin/arquibancada'
      path: '/arquibancada'
      fullPath: '/admin/arquibancada'
      preLoaderRoute: typeof AdminArquibancadaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArquibancadaRoute: typeof AdminArquibancadaRoute
  AdminLojasRoute: typeof AdminLojasRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArquibancadaRoute: AdminArquibancadaRoute,
  AdminLojasRoute: AdminLojasRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoacoesRouteChildren {
  DoacoesObrigadoRoute: typeof DoacoesObrigadoRoute
}

const DoacoesRouteChildren: DoacoesRouteChildren = {
  DoacoesObrigadoRoute: DoacoesObrigadoRoute,
}

const DoacoesRouteWithChildren =
  DoacoesRoute._addFileChildren(DoacoesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AreaCriancaRoute: AreaCriancaRoute,
  BeneficiosRoute: BeneficiosRoute,
  CadastroRoute: CadastroRoute,
  CompletarPerfilRoute: CompletarPerfilRoute,
  ContatoRoute: ContatoRoute,
  ConvideRoute: ConvideRoute,
  DoacoesRoute: DoacoesRouteWithChildren,
  EmpresarialRoute: EmpresarialRoute,
  IntegracaoNeuroinclusivaRoute: IntegracaoNeuroinclusivaRoute,
  LgpdRoute: LgpdRoute,
  LoginRoute: LoginRoute,
  MaoNaMassaRoute: MaoNaMassaRoute,
  MeuImpactoRoute: MeuImpactoRoute,
  MuralRoute: MuralRoute,
  NoticiasRoute: NoticiasRoute,
  NucleosRoute: NucleosRoute,
  ParceirosRoute: ParceirosRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProjetosRoute: ProjetosRoute,
  QuemSomosRoute: QuemSomosRoute,
  RankingRoute: RankingRoute,
  TermosRoute: TermosRoute,
  TorcidaRoute: TorcidaRoute,
  ValidarCarteirinhaRoute: ValidarCarteirinhaRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
